name: Sync from Mintplex-Labs/anything-llm

on:
  schedule:
    - cron: '0 3 * * *'  # runs every day at 03:00 UTC
  workflow_dispatch:      # allows manual run via GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Add upstream and fetch
        run: |
          git remote add upstream https://github.com/Mintplex-Labs/anything-llm.git
          git fetch upstream
          git checkout master  # or main, depending on your default branch
          git merge upstream/main --allow-unrelated-histories -m "🔄 Sync from upstream"
          
      - name: Push changes
        run: |
          git push origin master
